<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SDL3-CS.Tests\SDL3-CS.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <StaticWebAssetFingerprintPattern Include="JS" Pattern="*.js" Expression="#[.{fingerprint}]!" />
    <NativeFileReference Include="../native/browser-wasm/**/*.a" />
    <EmccExportedRuntimeMethod Include="requestFullscreen" />
  </ItemGroup>
</Project>
