/*
  <auto-generated/>
  C# bindings for Simple DirectMedia Layer.
  Original copyright notice of input files:

  Simple DirectMedia Layer
  Copyright (C) 1997-2024 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

namespace SDL
{
    public static partial class SDL3
    {
        [NativeTypeName("#define SDLK_SCANCODE_MASK (1u<<30)")]
        public const uint SDLK_SCANCODE_MASK = (1U << 30);

        [NativeTypeName("#define SDLK_UNKNOWN 0x00000000u")]
        public const uint SDLK_UNKNOWN = 0x00000000U;

        [NativeTypeName("#define SDLK_RETURN 0x0000000du")]
        public const uint SDLK_RETURN = 0x0000000dU;

        [NativeTypeName("#define SDLK_ESCAPE 0x0000001bu")]
        public const uint SDLK_ESCAPE = 0x0000001bU;

        [NativeTypeName("#define SDLK_BACKSPACE 0x00000008u")]
        public const uint SDLK_BACKSPACE = 0x00000008U;

        [NativeTypeName("#define SDLK_TAB 0x00000009u")]
        public const uint SDLK_TAB = 0x00000009U;

        [NativeTypeName("#define SDLK_SPACE 0x00000020u")]
        public const uint SDLK_SPACE = 0x00000020U;

        [NativeTypeName("#define SDLK_EXCLAIM 0x00000021u")]
        public const uint SDLK_EXCLAIM = 0x00000021U;

        [NativeTypeName("#define SDLK_DBLAPOSTROPHE 0x00000022u")]
        public const uint SDLK_DBLAPOSTROPHE = 0x00000022U;

        [NativeTypeName("#define SDLK_HASH 0x00000023u")]
        public const uint SDLK_HASH = 0x00000023U;

        [NativeTypeName("#define SDLK_DOLLAR 0x00000024u")]
        public const uint SDLK_DOLLAR = 0x00000024U;

        [NativeTypeName("#define SDLK_PERCENT 0x00000025u")]
        public const uint SDLK_PERCENT = 0x00000025U;

        [NativeTypeName("#define SDLK_AMPERSAND 0x00000026u")]
        public const uint SDLK_AMPERSAND = 0x00000026U;

        [NativeTypeName("#define SDLK_APOSTROPHE 0x00000027u")]
        public const uint SDLK_APOSTROPHE = 0x00000027U;

        [NativeTypeName("#define SDLK_LEFTPAREN 0x00000028u")]
        public const uint SDLK_LEFTPAREN = 0x00000028U;

        [NativeTypeName("#define SDLK_RIGHTPAREN 0x00000029u")]
        public const uint SDLK_RIGHTPAREN = 0x00000029U;

        [NativeTypeName("#define SDLK_ASTERISK 0x0000002au")]
        public const uint SDLK_ASTERISK = 0x0000002aU;

        [NativeTypeName("#define SDLK_PLUS 0x0000002bu")]
        public const uint SDLK_PLUS = 0x0000002bU;

        [NativeTypeName("#define SDLK_COMMA 0x0000002cu")]
        public const uint SDLK_COMMA = 0x0000002cU;

        [NativeTypeName("#define SDLK_MINUS 0x0000002du")]
        public const uint SDLK_MINUS = 0x0000002dU;

        [NativeTypeName("#define SDLK_PERIOD 0x0000002eu")]
        public const uint SDLK_PERIOD = 0x0000002eU;

        [NativeTypeName("#define SDLK_SLASH 0x0000002fu")]
        public const uint SDLK_SLASH = 0x0000002fU;

        [NativeTypeName("#define SDLK_0 0x00000030u")]
        public const uint SDLK_0 = 0x00000030U;

        [NativeTypeName("#define SDLK_1 0x00000031u")]
        public const uint SDLK_1 = 0x00000031U;

        [NativeTypeName("#define SDLK_2 0x00000032u")]
        public const uint SDLK_2 = 0x00000032U;

        [NativeTypeName("#define SDLK_3 0x00000033u")]
        public const uint SDLK_3 = 0x00000033U;

        [NativeTypeName("#define SDLK_4 0x00000034u")]
        public const uint SDLK_4 = 0x00000034U;

        [NativeTypeName("#define SDLK_5 0x00000035u")]
        public const uint SDLK_5 = 0x00000035U;

        [NativeTypeName("#define SDLK_6 0x00000036u")]
        public const uint SDLK_6 = 0x00000036U;

        [NativeTypeName("#define SDLK_7 0x00000037u")]
        public const uint SDLK_7 = 0x00000037U;

        [NativeTypeName("#define SDLK_8 0x00000038u")]
        public const uint SDLK_8 = 0x00000038U;

        [NativeTypeName("#define SDLK_9 0x00000039u")]
        public const uint SDLK_9 = 0x00000039U;

        [NativeTypeName("#define SDLK_COLON 0x0000003au")]
        public const uint SDLK_COLON = 0x0000003aU;

        [NativeTypeName("#define SDLK_SEMICOLON 0x0000003bu")]
        public const uint SDLK_SEMICOLON = 0x0000003bU;

        [NativeTypeName("#define SDLK_LESS 0x0000003cu")]
        public const uint SDLK_LESS = 0x0000003cU;

        [NativeTypeName("#define SDLK_EQUALS 0x0000003du")]
        public const uint SDLK_EQUALS = 0x0000003dU;

        [NativeTypeName("#define SDLK_GREATER 0x0000003eu")]
        public const uint SDLK_GREATER = 0x0000003eU;

        [NativeTypeName("#define SDLK_QUESTION 0x0000003fu")]
        public const uint SDLK_QUESTION = 0x0000003fU;

        [NativeTypeName("#define SDLK_AT 0x00000040u")]
        public const uint SDLK_AT = 0x00000040U;

        [NativeTypeName("#define SDLK_LEFTBRACKET 0x0000005bu")]
        public const uint SDLK_LEFTBRACKET = 0x0000005bU;

        [NativeTypeName("#define SDLK_BACKSLASH 0x0000005cu")]
        public const uint SDLK_BACKSLASH = 0x0000005cU;

        [NativeTypeName("#define SDLK_RIGHTBRACKET 0x0000005du")]
        public const uint SDLK_RIGHTBRACKET = 0x0000005dU;

        [NativeTypeName("#define SDLK_CARET 0x0000005eu")]
        public const uint SDLK_CARET = 0x0000005eU;

        [NativeTypeName("#define SDLK_UNDERSCORE 0x0000005fu")]
        public const uint SDLK_UNDERSCORE = 0x0000005fU;

        [NativeTypeName("#define SDLK_GRAVE 0x00000060u")]
        public const uint SDLK_GRAVE = 0x00000060U;

        [NativeTypeName("#define SDLK_A 0x00000061u")]
        public const uint SDLK_A = 0x00000061U;

        [NativeTypeName("#define SDLK_B 0x00000062u")]
        public const uint SDLK_B = 0x00000062U;

        [NativeTypeName("#define SDLK_C 0x00000063u")]
        public const uint SDLK_C = 0x00000063U;

        [NativeTypeName("#define SDLK_D 0x00000064u")]
        public const uint SDLK_D = 0x00000064U;

        [NativeTypeName("#define SDLK_E 0x00000065u")]
        public const uint SDLK_E = 0x00000065U;

        [NativeTypeName("#define SDLK_F 0x00000066u")]
        public const uint SDLK_F = 0x00000066U;

        [NativeTypeName("#define SDLK_G 0x00000067u")]
        public const uint SDLK_G = 0x00000067U;

        [NativeTypeName("#define SDLK_H 0x00000068u")]
        public const uint SDLK_H = 0x00000068U;

        [NativeTypeName("#define SDLK_I 0x00000069u")]
        public const uint SDLK_I = 0x00000069U;

        [NativeTypeName("#define SDLK_J 0x0000006au")]
        public const uint SDLK_J = 0x0000006aU;

        [NativeTypeName("#define SDLK_K 0x0000006bu")]
        public const uint SDLK_K = 0x0000006bU;

        [NativeTypeName("#define SDLK_L 0x0000006cu")]
        public const uint SDLK_L = 0x0000006cU;

        [NativeTypeName("#define SDLK_M 0x0000006du")]
        public const uint SDLK_M = 0x0000006dU;

        [NativeTypeName("#define SDLK_N 0x0000006eu")]
        public const uint SDLK_N = 0x0000006eU;

        [NativeTypeName("#define SDLK_O 0x0000006fu")]
        public const uint SDLK_O = 0x0000006fU;

        [NativeTypeName("#define SDLK_P 0x00000070u")]
        public const uint SDLK_P = 0x00000070U;

        [NativeTypeName("#define SDLK_Q 0x00000071u")]
        public const uint SDLK_Q = 0x00000071U;

        [NativeTypeName("#define SDLK_R 0x00000072u")]
        public const uint SDLK_R = 0x00000072U;

        [NativeTypeName("#define SDLK_S 0x00000073u")]
        public const uint SDLK_S = 0x00000073U;

        [NativeTypeName("#define SDLK_T 0x00000074u")]
        public const uint SDLK_T = 0x00000074U;

        [NativeTypeName("#define SDLK_U 0x00000075u")]
        public const uint SDLK_U = 0x00000075U;

        [NativeTypeName("#define SDLK_V 0x00000076u")]
        public const uint SDLK_V = 0x00000076U;

        [NativeTypeName("#define SDLK_W 0x00000077u")]
        public const uint SDLK_W = 0x00000077U;

        [NativeTypeName("#define SDLK_X 0x00000078u")]
        public const uint SDLK_X = 0x00000078U;

        [NativeTypeName("#define SDLK_Y 0x00000079u")]
        public const uint SDLK_Y = 0x00000079U;

        [NativeTypeName("#define SDLK_Z 0x0000007au")]
        public const uint SDLK_Z = 0x0000007aU;

        [NativeTypeName("#define SDLK_LEFTBRACE 0x0000007bu")]
        public const uint SDLK_LEFTBRACE = 0x0000007bU;

        [NativeTypeName("#define SDLK_PIPE 0x0000007cu")]
        public const uint SDLK_PIPE = 0x0000007cU;

        [NativeTypeName("#define SDLK_RIGHTBRACE 0x0000007du")]
        public const uint SDLK_RIGHTBRACE = 0x0000007dU;

        [NativeTypeName("#define SDLK_TILDE 0x0000007eu")]
        public const uint SDLK_TILDE = 0x0000007eU;

        [NativeTypeName("#define SDLK_DELETE 0x0000007fu")]
        public const uint SDLK_DELETE = 0x0000007fU;

        [NativeTypeName("#define SDLK_PLUSMINUS 0x000000b1u")]
        public const uint SDLK_PLUSMINUS = 0x000000b1U;

        [NativeTypeName("#define SDLK_CAPSLOCK 0x40000039u")]
        public const uint SDLK_CAPSLOCK = 0x40000039U;

        [NativeTypeName("#define SDLK_F1 0x4000003au")]
        public const uint SDLK_F1 = 0x4000003aU;

        [NativeTypeName("#define SDLK_F2 0x4000003bu")]
        public const uint SDLK_F2 = 0x4000003bU;

        [NativeTypeName("#define SDLK_F3 0x4000003cu")]
        public const uint SDLK_F3 = 0x4000003cU;

        [NativeTypeName("#define SDLK_F4 0x4000003du")]
        public const uint SDLK_F4 = 0x4000003dU;

        [NativeTypeName("#define SDLK_F5 0x4000003eu")]
        public const uint SDLK_F5 = 0x4000003eU;

        [NativeTypeName("#define SDLK_F6 0x4000003fu")]
        public const uint SDLK_F6 = 0x4000003fU;

        [NativeTypeName("#define SDLK_F7 0x40000040u")]
        public const uint SDLK_F7 = 0x40000040U;

        [NativeTypeName("#define SDLK_F8 0x40000041u")]
        public const uint SDLK_F8 = 0x40000041U;

        [NativeTypeName("#define SDLK_F9 0x40000042u")]
        public const uint SDLK_F9 = 0x40000042U;

        [NativeTypeName("#define SDLK_F10 0x40000043u")]
        public const uint SDLK_F10 = 0x40000043U;

        [NativeTypeName("#define SDLK_F11 0x40000044u")]
        public const uint SDLK_F11 = 0x40000044U;

        [NativeTypeName("#define SDLK_F12 0x40000045u")]
        public const uint SDLK_F12 = 0x40000045U;

        [NativeTypeName("#define SDLK_PRINTSCREEN 0x40000046u")]
        public const uint SDLK_PRINTSCREEN = 0x40000046U;

        [NativeTypeName("#define SDLK_SCROLLLOCK 0x40000047u")]
        public const uint SDLK_SCROLLLOCK = 0x40000047U;

        [NativeTypeName("#define SDLK_PAUSE 0x40000048u")]
        public const uint SDLK_PAUSE = 0x40000048U;

        [NativeTypeName("#define SDLK_INSERT 0x40000049u")]
        public const uint SDLK_INSERT = 0x40000049U;

        [NativeTypeName("#define SDLK_HOME 0x4000004au")]
        public const uint SDLK_HOME = 0x4000004aU;

        [NativeTypeName("#define SDLK_PAGEUP 0x4000004bu")]
        public const uint SDLK_PAGEUP = 0x4000004bU;

        [NativeTypeName("#define SDLK_END 0x4000004du")]
        public const uint SDLK_END = 0x4000004dU;

        [NativeTypeName("#define SDLK_PAGEDOWN 0x4000004eu")]
        public const uint SDLK_PAGEDOWN = 0x4000004eU;

        [NativeTypeName("#define SDLK_RIGHT 0x4000004fu")]
        public const uint SDLK_RIGHT = 0x4000004fU;

        [NativeTypeName("#define SDLK_LEFT 0x40000050u")]
        public const uint SDLK_LEFT = 0x40000050U;

        [NativeTypeName("#define SDLK_DOWN 0x40000051u")]
        public const uint SDLK_DOWN = 0x40000051U;

        [NativeTypeName("#define SDLK_UP 0x40000052u")]
        public const uint SDLK_UP = 0x40000052U;

        [NativeTypeName("#define SDLK_NUMLOCKCLEAR 0x40000053u")]
        public const uint SDLK_NUMLOCKCLEAR = 0x40000053U;

        [NativeTypeName("#define SDLK_KP_DIVIDE 0x40000054u")]
        public const uint SDLK_KP_DIVIDE = 0x40000054U;

        [NativeTypeName("#define SDLK_KP_MULTIPLY 0x40000055u")]
        public const uint SDLK_KP_MULTIPLY = 0x40000055U;

        [NativeTypeName("#define SDLK_KP_MINUS 0x40000056u")]
        public const uint SDLK_KP_MINUS = 0x40000056U;

        [NativeTypeName("#define SDLK_KP_PLUS 0x40000057u")]
        public const uint SDLK_KP_PLUS = 0x40000057U;

        [NativeTypeName("#define SDLK_KP_ENTER 0x40000058u")]
        public const uint SDLK_KP_ENTER = 0x40000058U;

        [NativeTypeName("#define SDLK_KP_1 0x40000059u")]
        public const uint SDLK_KP_1 = 0x40000059U;

        [NativeTypeName("#define SDLK_KP_2 0x4000005au")]
        public const uint SDLK_KP_2 = 0x4000005aU;

        [NativeTypeName("#define SDLK_KP_3 0x4000005bu")]
        public const uint SDLK_KP_3 = 0x4000005bU;

        [NativeTypeName("#define SDLK_KP_4 0x4000005cu")]
        public const uint SDLK_KP_4 = 0x4000005cU;

        [NativeTypeName("#define SDLK_KP_5 0x4000005du")]
        public const uint SDLK_KP_5 = 0x4000005dU;

        [NativeTypeName("#define SDLK_KP_6 0x4000005eu")]
        public const uint SDLK_KP_6 = 0x4000005eU;

        [NativeTypeName("#define SDLK_KP_7 0x4000005fu")]
        public const uint SDLK_KP_7 = 0x4000005fU;

        [NativeTypeName("#define SDLK_KP_8 0x40000060u")]
        public const uint SDLK_KP_8 = 0x40000060U;

        [NativeTypeName("#define SDLK_KP_9 0x40000061u")]
        public const uint SDLK_KP_9 = 0x40000061U;

        [NativeTypeName("#define SDLK_KP_0 0x40000062u")]
        public const uint SDLK_KP_0 = 0x40000062U;

        [NativeTypeName("#define SDLK_KP_PERIOD 0x40000063u")]
        public const uint SDLK_KP_PERIOD = 0x40000063U;

        [NativeTypeName("#define SDLK_APPLICATION 0x40000065u")]
        public const uint SDLK_APPLICATION = 0x40000065U;

        [NativeTypeName("#define SDLK_POWER 0x40000066u")]
        public const uint SDLK_POWER = 0x40000066U;

        [NativeTypeName("#define SDLK_KP_EQUALS 0x40000067u")]
        public const uint SDLK_KP_EQUALS = 0x40000067U;

        [NativeTypeName("#define SDLK_F13 0x40000068u")]
        public const uint SDLK_F13 = 0x40000068U;

        [NativeTypeName("#define SDLK_F14 0x40000069u")]
        public const uint SDLK_F14 = 0x40000069U;

        [NativeTypeName("#define SDLK_F15 0x4000006au")]
        public const uint SDLK_F15 = 0x4000006aU;

        [NativeTypeName("#define SDLK_F16 0x4000006bu")]
        public const uint SDLK_F16 = 0x4000006bU;

        [NativeTypeName("#define SDLK_F17 0x4000006cu")]
        public const uint SDLK_F17 = 0x4000006cU;

        [NativeTypeName("#define SDLK_F18 0x4000006du")]
        public const uint SDLK_F18 = 0x4000006dU;

        [NativeTypeName("#define SDLK_F19 0x4000006eu")]
        public const uint SDLK_F19 = 0x4000006eU;

        [NativeTypeName("#define SDLK_F20 0x4000006fu")]
        public const uint SDLK_F20 = 0x4000006fU;

        [NativeTypeName("#define SDLK_F21 0x40000070u")]
        public const uint SDLK_F21 = 0x40000070U;

        [NativeTypeName("#define SDLK_F22 0x40000071u")]
        public const uint SDLK_F22 = 0x40000071U;

        [NativeTypeName("#define SDLK_F23 0x40000072u")]
        public const uint SDLK_F23 = 0x40000072U;

        [NativeTypeName("#define SDLK_F24 0x40000073u")]
        public const uint SDLK_F24 = 0x40000073U;

        [NativeTypeName("#define SDLK_EXECUTE 0x40000074u")]
        public const uint SDLK_EXECUTE = 0x40000074U;

        [NativeTypeName("#define SDLK_HELP 0x40000075u")]
        public const uint SDLK_HELP = 0x40000075U;

        [NativeTypeName("#define SDLK_MENU 0x40000076u")]
        public const uint SDLK_MENU = 0x40000076U;

        [NativeTypeName("#define SDLK_SELECT 0x40000077u")]
        public const uint SDLK_SELECT = 0x40000077U;

        [NativeTypeName("#define SDLK_STOP 0x40000078u")]
        public const uint SDLK_STOP = 0x40000078U;

        [NativeTypeName("#define SDLK_AGAIN 0x40000079u")]
        public const uint SDLK_AGAIN = 0x40000079U;

        [NativeTypeName("#define SDLK_UNDO 0x4000007au")]
        public const uint SDLK_UNDO = 0x4000007aU;

        [NativeTypeName("#define SDLK_CUT 0x4000007bu")]
        public const uint SDLK_CUT = 0x4000007bU;

        [NativeTypeName("#define SDLK_COPY 0x4000007cu")]
        public const uint SDLK_COPY = 0x4000007cU;

        [NativeTypeName("#define SDLK_PASTE 0x4000007du")]
        public const uint SDLK_PASTE = 0x4000007dU;

        [NativeTypeName("#define SDLK_FIND 0x4000007eu")]
        public const uint SDLK_FIND = 0x4000007eU;

        [NativeTypeName("#define SDLK_MUTE 0x4000007fu")]
        public const uint SDLK_MUTE = 0x4000007fU;

        [NativeTypeName("#define SDLK_VOLUMEUP 0x40000080u")]
        public const uint SDLK_VOLUMEUP = 0x40000080U;

        [NativeTypeName("#define SDLK_VOLUMEDOWN 0x40000081u")]
        public const uint SDLK_VOLUMEDOWN = 0x40000081U;

        [NativeTypeName("#define SDLK_KP_COMMA 0x40000085u")]
        public const uint SDLK_KP_COMMA = 0x40000085U;

        [NativeTypeName("#define SDLK_KP_EQUALSAS400 0x40000086u")]
        public const uint SDLK_KP_EQUALSAS400 = 0x40000086U;

        [NativeTypeName("#define SDLK_ALTERASE 0x40000099u")]
        public const uint SDLK_ALTERASE = 0x40000099U;

        [NativeTypeName("#define SDLK_SYSREQ 0x4000009au")]
        public const uint SDLK_SYSREQ = 0x4000009aU;

        [NativeTypeName("#define SDLK_CANCEL 0x4000009bu")]
        public const uint SDLK_CANCEL = 0x4000009bU;

        [NativeTypeName("#define SDLK_CLEAR 0x4000009cu")]
        public const uint SDLK_CLEAR = 0x4000009cU;

        [NativeTypeName("#define SDLK_PRIOR 0x4000009du")]
        public const uint SDLK_PRIOR = 0x4000009dU;

        [NativeTypeName("#define SDLK_RETURN2 0x4000009eu")]
        public const uint SDLK_RETURN2 = 0x4000009eU;

        [NativeTypeName("#define SDLK_SEPARATOR 0x4000009fu")]
        public const uint SDLK_SEPARATOR = 0x4000009fU;

        [NativeTypeName("#define SDLK_OUT 0x400000a0u")]
        public const uint SDLK_OUT = 0x400000a0U;

        [NativeTypeName("#define SDLK_OPER 0x400000a1u")]
        public const uint SDLK_OPER = 0x400000a1U;

        [NativeTypeName("#define SDLK_CLEARAGAIN 0x400000a2u")]
        public const uint SDLK_CLEARAGAIN = 0x400000a2U;

        [NativeTypeName("#define SDLK_CRSEL 0x400000a3u")]
        public const uint SDLK_CRSEL = 0x400000a3U;

        [NativeTypeName("#define SDLK_EXSEL 0x400000a4u")]
        public const uint SDLK_EXSEL = 0x400000a4U;

        [NativeTypeName("#define SDLK_KP_00 0x400000b0u")]
        public const uint SDLK_KP_00 = 0x400000b0U;

        [NativeTypeName("#define SDLK_KP_000 0x400000b1u")]
        public const uint SDLK_KP_000 = 0x400000b1U;

        [NativeTypeName("#define SDLK_THOUSANDSSEPARATOR 0x400000b2u")]
        public const uint SDLK_THOUSANDSSEPARATOR = 0x400000b2U;

        [NativeTypeName("#define SDLK_DECIMALSEPARATOR 0x400000b3u")]
        public const uint SDLK_DECIMALSEPARATOR = 0x400000b3U;

        [NativeTypeName("#define SDLK_CURRENCYUNIT 0x400000b4u")]
        public const uint SDLK_CURRENCYUNIT = 0x400000b4U;

        [NativeTypeName("#define SDLK_CURRENCYSUBUNIT 0x400000b5u")]
        public const uint SDLK_CURRENCYSUBUNIT = 0x400000b5U;

        [NativeTypeName("#define SDLK_KP_LEFTPAREN 0x400000b6u")]
        public const uint SDLK_KP_LEFTPAREN = 0x400000b6U;

        [NativeTypeName("#define SDLK_KP_RIGHTPAREN 0x400000b7u")]
        public const uint SDLK_KP_RIGHTPAREN = 0x400000b7U;

        [NativeTypeName("#define SDLK_KP_LEFTBRACE 0x400000b8u")]
        public const uint SDLK_KP_LEFTBRACE = 0x400000b8U;

        [NativeTypeName("#define SDLK_KP_RIGHTBRACE 0x400000b9u")]
        public const uint SDLK_KP_RIGHTBRACE = 0x400000b9U;

        [NativeTypeName("#define SDLK_KP_TAB 0x400000bau")]
        public const uint SDLK_KP_TAB = 0x400000baU;

        [NativeTypeName("#define SDLK_KP_BACKSPACE 0x400000bbu")]
        public const uint SDLK_KP_BACKSPACE = 0x400000bbU;

        [NativeTypeName("#define SDLK_KP_A 0x400000bcu")]
        public const uint SDLK_KP_A = 0x400000bcU;

        [NativeTypeName("#define SDLK_KP_B 0x400000bdu")]
        public const uint SDLK_KP_B = 0x400000bdU;

        [NativeTypeName("#define SDLK_KP_C 0x400000beu")]
        public const uint SDLK_KP_C = 0x400000beU;

        [NativeTypeName("#define SDLK_KP_D 0x400000bfu")]
        public const uint SDLK_KP_D = 0x400000bfU;

        [NativeTypeName("#define SDLK_KP_E 0x400000c0u")]
        public const uint SDLK_KP_E = 0x400000c0U;

        [NativeTypeName("#define SDLK_KP_F 0x400000c1u")]
        public const uint SDLK_KP_F = 0x400000c1U;

        [NativeTypeName("#define SDLK_KP_XOR 0x400000c2u")]
        public const uint SDLK_KP_XOR = 0x400000c2U;

        [NativeTypeName("#define SDLK_KP_POWER 0x400000c3u")]
        public const uint SDLK_KP_POWER = 0x400000c3U;

        [NativeTypeName("#define SDLK_KP_PERCENT 0x400000c4u")]
        public const uint SDLK_KP_PERCENT = 0x400000c4U;

        [NativeTypeName("#define SDLK_KP_LESS 0x400000c5u")]
        public const uint SDLK_KP_LESS = 0x400000c5U;

        [NativeTypeName("#define SDLK_KP_GREATER 0x400000c6u")]
        public const uint SDLK_KP_GREATER = 0x400000c6U;

        [NativeTypeName("#define SDLK_KP_AMPERSAND 0x400000c7u")]
        public const uint SDLK_KP_AMPERSAND = 0x400000c7U;

        [NativeTypeName("#define SDLK_KP_DBLAMPERSAND 0x400000c8u")]
        public const uint SDLK_KP_DBLAMPERSAND = 0x400000c8U;

        [NativeTypeName("#define SDLK_KP_VERTICALBAR 0x400000c9u")]
        public const uint SDLK_KP_VERTICALBAR = 0x400000c9U;

        [NativeTypeName("#define SDLK_KP_DBLVERTICALBAR 0x400000cau")]
        public const uint SDLK_KP_DBLVERTICALBAR = 0x400000caU;

        [NativeTypeName("#define SDLK_KP_COLON 0x400000cbu")]
        public const uint SDLK_KP_COLON = 0x400000cbU;

        [NativeTypeName("#define SDLK_KP_HASH 0x400000ccu")]
        public const uint SDLK_KP_HASH = 0x400000ccU;

        [NativeTypeName("#define SDLK_KP_SPACE 0x400000cdu")]
        public const uint SDLK_KP_SPACE = 0x400000cdU;

        [NativeTypeName("#define SDLK_KP_AT 0x400000ceu")]
        public const uint SDLK_KP_AT = 0x400000ceU;

        [NativeTypeName("#define SDLK_KP_EXCLAM 0x400000cfu")]
        public const uint SDLK_KP_EXCLAM = 0x400000cfU;

        [NativeTypeName("#define SDLK_KP_MEMSTORE 0x400000d0u")]
        public const uint SDLK_KP_MEMSTORE = 0x400000d0U;

        [NativeTypeName("#define SDLK_KP_MEMRECALL 0x400000d1u")]
        public const uint SDLK_KP_MEMRECALL = 0x400000d1U;

        [NativeTypeName("#define SDLK_KP_MEMCLEAR 0x400000d2u")]
        public const uint SDLK_KP_MEMCLEAR = 0x400000d2U;

        [NativeTypeName("#define SDLK_KP_MEMADD 0x400000d3u")]
        public const uint SDLK_KP_MEMADD = 0x400000d3U;

        [NativeTypeName("#define SDLK_KP_MEMSUBTRACT 0x400000d4u")]
        public const uint SDLK_KP_MEMSUBTRACT = 0x400000d4U;

        [NativeTypeName("#define SDLK_KP_MEMMULTIPLY 0x400000d5u")]
        public const uint SDLK_KP_MEMMULTIPLY = 0x400000d5U;

        [NativeTypeName("#define SDLK_KP_MEMDIVIDE 0x400000d6u")]
        public const uint SDLK_KP_MEMDIVIDE = 0x400000d6U;

        [NativeTypeName("#define SDLK_KP_PLUSMINUS 0x400000d7u")]
        public const uint SDLK_KP_PLUSMINUS = 0x400000d7U;

        [NativeTypeName("#define SDLK_KP_CLEAR 0x400000d8u")]
        public const uint SDLK_KP_CLEAR = 0x400000d8U;

        [NativeTypeName("#define SDLK_KP_CLEARENTRY 0x400000d9u")]
        public const uint SDLK_KP_CLEARENTRY = 0x400000d9U;

        [NativeTypeName("#define SDLK_KP_BINARY 0x400000dau")]
        public const uint SDLK_KP_BINARY = 0x400000daU;

        [NativeTypeName("#define SDLK_KP_OCTAL 0x400000dbu")]
        public const uint SDLK_KP_OCTAL = 0x400000dbU;

        [NativeTypeName("#define SDLK_KP_DECIMAL 0x400000dcu")]
        public const uint SDLK_KP_DECIMAL = 0x400000dcU;

        [NativeTypeName("#define SDLK_KP_HEXADECIMAL 0x400000ddu")]
        public const uint SDLK_KP_HEXADECIMAL = 0x400000ddU;

        [NativeTypeName("#define SDLK_LCTRL 0x400000e0u")]
        public const uint SDLK_LCTRL = 0x400000e0U;

        [NativeTypeName("#define SDLK_LSHIFT 0x400000e1u")]
        public const uint SDLK_LSHIFT = 0x400000e1U;

        [NativeTypeName("#define SDLK_LALT 0x400000e2u")]
        public const uint SDLK_LALT = 0x400000e2U;

        [NativeTypeName("#define SDLK_LGUI 0x400000e3u")]
        public const uint SDLK_LGUI = 0x400000e3U;

        [NativeTypeName("#define SDLK_RCTRL 0x400000e4u")]
        public const uint SDLK_RCTRL = 0x400000e4U;

        [NativeTypeName("#define SDLK_RSHIFT 0x400000e5u")]
        public const uint SDLK_RSHIFT = 0x400000e5U;

        [NativeTypeName("#define SDLK_RALT 0x400000e6u")]
        public const uint SDLK_RALT = 0x400000e6U;

        [NativeTypeName("#define SDLK_RGUI 0x400000e7u")]
        public const uint SDLK_RGUI = 0x400000e7U;

        [NativeTypeName("#define SDLK_MODE 0x40000101u")]
        public const uint SDLK_MODE = 0x40000101U;

        [NativeTypeName("#define SDLK_SLEEP 0x40000102u")]
        public const uint SDLK_SLEEP = 0x40000102U;

        [NativeTypeName("#define SDLK_WAKE 0x40000103u")]
        public const uint SDLK_WAKE = 0x40000103U;

        [NativeTypeName("#define SDLK_CHANNEL_INCREMENT 0x40000104u")]
        public const uint SDLK_CHANNEL_INCREMENT = 0x40000104U;

        [NativeTypeName("#define SDLK_CHANNEL_DECREMENT 0x40000105u")]
        public const uint SDLK_CHANNEL_DECREMENT = 0x40000105U;

        [NativeTypeName("#define SDLK_MEDIA_PLAY 0x40000106u")]
        public const uint SDLK_MEDIA_PLAY = 0x40000106U;

        [NativeTypeName("#define SDLK_MEDIA_PAUSE 0x40000107u")]
        public const uint SDLK_MEDIA_PAUSE = 0x40000107U;

        [NativeTypeName("#define SDLK_MEDIA_RECORD 0x40000108u")]
        public const uint SDLK_MEDIA_RECORD = 0x40000108U;

        [NativeTypeName("#define SDLK_MEDIA_FAST_FORWARD 0x40000109u")]
        public const uint SDLK_MEDIA_FAST_FORWARD = 0x40000109U;

        [NativeTypeName("#define SDLK_MEDIA_REWIND 0x4000010au")]
        public const uint SDLK_MEDIA_REWIND = 0x4000010aU;

        [NativeTypeName("#define SDLK_MEDIA_NEXT_TRACK 0x4000010bu")]
        public const uint SDLK_MEDIA_NEXT_TRACK = 0x4000010bU;

        [NativeTypeName("#define SDLK_MEDIA_PREVIOUS_TRACK 0x4000010cu")]
        public const uint SDLK_MEDIA_PREVIOUS_TRACK = 0x4000010cU;

        [NativeTypeName("#define SDLK_MEDIA_STOP 0x4000010du")]
        public const uint SDLK_MEDIA_STOP = 0x4000010dU;

        [NativeTypeName("#define SDLK_MEDIA_EJECT 0x4000010eu")]
        public const uint SDLK_MEDIA_EJECT = 0x4000010eU;

        [NativeTypeName("#define SDLK_MEDIA_PLAY_PAUSE 0x4000010fu")]
        public const uint SDLK_MEDIA_PLAY_PAUSE = 0x4000010fU;

        [NativeTypeName("#define SDLK_MEDIA_SELECT 0x40000110u")]
        public const uint SDLK_MEDIA_SELECT = 0x40000110U;

        [NativeTypeName("#define SDLK_AC_NEW 0x40000111u")]
        public const uint SDLK_AC_NEW = 0x40000111U;

        [NativeTypeName("#define SDLK_AC_OPEN 0x40000112u")]
        public const uint SDLK_AC_OPEN = 0x40000112U;

        [NativeTypeName("#define SDLK_AC_CLOSE 0x40000113u")]
        public const uint SDLK_AC_CLOSE = 0x40000113U;

        [NativeTypeName("#define SDLK_AC_EXIT 0x40000114u")]
        public const uint SDLK_AC_EXIT = 0x40000114U;

        [NativeTypeName("#define SDLK_AC_SAVE 0x40000115u")]
        public const uint SDLK_AC_SAVE = 0x40000115U;

        [NativeTypeName("#define SDLK_AC_PRINT 0x40000116u")]
        public const uint SDLK_AC_PRINT = 0x40000116U;

        [NativeTypeName("#define SDLK_AC_PROPERTIES 0x40000117u")]
        public const uint SDLK_AC_PROPERTIES = 0x40000117U;

        [NativeTypeName("#define SDLK_AC_SEARCH 0x40000118u")]
        public const uint SDLK_AC_SEARCH = 0x40000118U;

        [NativeTypeName("#define SDLK_AC_HOME 0x40000119u")]
        public const uint SDLK_AC_HOME = 0x40000119U;

        [NativeTypeName("#define SDLK_AC_BACK 0x4000011au")]
        public const uint SDLK_AC_BACK = 0x4000011aU;

        [NativeTypeName("#define SDLK_AC_FORWARD 0x4000011bu")]
        public const uint SDLK_AC_FORWARD = 0x4000011bU;

        [NativeTypeName("#define SDLK_AC_STOP 0x4000011cu")]
        public const uint SDLK_AC_STOP = 0x4000011cU;

        [NativeTypeName("#define SDLK_AC_REFRESH 0x4000011du")]
        public const uint SDLK_AC_REFRESH = 0x4000011dU;

        [NativeTypeName("#define SDLK_AC_BOOKMARKS 0x4000011eu")]
        public const uint SDLK_AC_BOOKMARKS = 0x4000011eU;

        [NativeTypeName("#define SDLK_SOFTLEFT 0x4000011fu")]
        public const uint SDLK_SOFTLEFT = 0x4000011fU;

        [NativeTypeName("#define SDLK_SOFTRIGHT 0x40000120u")]
        public const uint SDLK_SOFTRIGHT = 0x40000120U;

        [NativeTypeName("#define SDLK_CALL 0x40000121u")]
        public const uint SDLK_CALL = 0x40000121U;

        [NativeTypeName("#define SDLK_ENDCALL 0x40000122u")]
        public const uint SDLK_ENDCALL = 0x40000122U;

        [NativeTypeName("#define SDL_KMOD_NONE 0x0000u")]
        public const uint SDL_KMOD_NONE = 0x0000U;

        [NativeTypeName("#define SDL_KMOD_LSHIFT 0x0001u")]
        public const uint SDL_KMOD_LSHIFT = 0x0001U;

        [NativeTypeName("#define SDL_KMOD_RSHIFT 0x0002u")]
        public const uint SDL_KMOD_RSHIFT = 0x0002U;

        [NativeTypeName("#define SDL_KMOD_LCTRL 0x0040u")]
        public const uint SDL_KMOD_LCTRL = 0x0040U;

        [NativeTypeName("#define SDL_KMOD_RCTRL 0x0080u")]
        public const uint SDL_KMOD_RCTRL = 0x0080U;

        [NativeTypeName("#define SDL_KMOD_LALT 0x0100u")]
        public const uint SDL_KMOD_LALT = 0x0100U;

        [NativeTypeName("#define SDL_KMOD_RALT 0x0200u")]
        public const uint SDL_KMOD_RALT = 0x0200U;

        [NativeTypeName("#define SDL_KMOD_LGUI 0x0400u")]
        public const uint SDL_KMOD_LGUI = 0x0400U;

        [NativeTypeName("#define SDL_KMOD_RGUI 0x0800u")]
        public const uint SDL_KMOD_RGUI = 0x0800U;

        [NativeTypeName("#define SDL_KMOD_NUM 0x1000u")]
        public const uint SDL_KMOD_NUM = 0x1000U;

        [NativeTypeName("#define SDL_KMOD_CAPS 0x2000u")]
        public const uint SDL_KMOD_CAPS = 0x2000U;

        [NativeTypeName("#define SDL_KMOD_MODE 0x4000u")]
        public const uint SDL_KMOD_MODE = 0x4000U;

        [NativeTypeName("#define SDL_KMOD_SCROLL 0x8000u")]
        public const uint SDL_KMOD_SCROLL = 0x8000U;

        [NativeTypeName("#define SDL_KMOD_CTRL (SDL_KMOD_LCTRL | SDL_KMOD_RCTRL)")]
        public const uint SDL_KMOD_CTRL = (0x0040U | 0x0080U);

        [NativeTypeName("#define SDL_KMOD_SHIFT (SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT)")]
        public const uint SDL_KMOD_SHIFT = (0x0001U | 0x0002U);

        [NativeTypeName("#define SDL_KMOD_ALT (SDL_KMOD_LALT | SDL_KMOD_RALT)")]
        public const uint SDL_KMOD_ALT = (0x0100U | 0x0200U);

        [NativeTypeName("#define SDL_KMOD_GUI (SDL_KMOD_LGUI | SDL_KMOD_RGUI)")]
        public const uint SDL_KMOD_GUI = (0x0400U | 0x0800U);
    }
}
