/*
  <auto-generated/>
  C# bindings for Simple DirectMedia Layer.
  Original copyright notice of input files:

  Simple DirectMedia Layer
  Copyright (C) 1997-2024 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

using System.Runtime.InteropServices;

namespace SDL
{
    public enum SDL_PenAxis
    {
        SDL_PEN_AXIS_PRESSURE,
        SDL_PEN_AXIS_XTILT,
        SDL_PEN_AXIS_YTILT,
        SDL_PEN_AXIS_DISTANCE,
        SDL_PEN_AXIS_ROTATION,
        SDL_PEN_AXIS_SLIDER,
        SDL_PEN_AXIS_TANGENTIAL_PRESSURE,
        SDL_PEN_AXIS_COUNT,
    }

    public enum SDL_PenDeviceType
    {
        SDL_PEN_DEVICE_TYPE_INVALID = -1,
        SDL_PEN_DEVICE_TYPE_UNKNOWN,
        SDL_PEN_DEVICE_TYPE_DIRECT,
        SDL_PEN_DEVICE_TYPE_INDIRECT,
    }

    public static partial class SDL3
    {
        [DllImport("SDL3", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern SDL_PenDeviceType SDL_GetPenDeviceType(SDL_PenID instance_id);

        [NativeTypeName("#define SDL_PEN_INPUT_DOWN (1u << 0)")]
        public const uint SDL_PEN_INPUT_DOWN = (1U << 0);

        [NativeTypeName("#define SDL_PEN_INPUT_BUTTON_1 (1u << 1)")]
        public const uint SDL_PEN_INPUT_BUTTON_1 = (1U << 1);

        [NativeTypeName("#define SDL_PEN_INPUT_BUTTON_2 (1u << 2)")]
        public const uint SDL_PEN_INPUT_BUTTON_2 = (1U << 2);

        [NativeTypeName("#define SDL_PEN_INPUT_BUTTON_3 (1u << 3)")]
        public const uint SDL_PEN_INPUT_BUTTON_3 = (1U << 3);

        [NativeTypeName("#define SDL_PEN_INPUT_BUTTON_4 (1u << 4)")]
        public const uint SDL_PEN_INPUT_BUTTON_4 = (1U << 4);

        [NativeTypeName("#define SDL_PEN_INPUT_BUTTON_5 (1u << 5)")]
        public const uint SDL_PEN_INPUT_BUTTON_5 = (1U << 5);

        [NativeTypeName("#define SDL_PEN_INPUT_ERASER_TIP (1u << 30)")]
        public const uint SDL_PEN_INPUT_ERASER_TIP = (1U << 30);
    }
}
