name: cross compile linux

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["amd64/ubuntu", "arm64v8/ubuntu", "i386/ubuntu", "arm32v7/ubuntu"]
    steps:
      -
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL'
          ref: 'main'
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Run build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.container }}
          options: -v ${{ github.workspace }}:/workspace
          run: |
            echo "Hello World!"
            uname -a
            ls /workspace

            apt install -y \
              gcc-multilib \
              g++-multilib \
              cmake \
              ninja-build \
              wayland-scanner++ \
              wayland-protocols \
              pkg-config \
              libasound2-dev \
              libdbus-1-dev \
              libegl1-mesa-dev \
              libgl1-mesa-dev \
              libgles2-mesa-dev \
              libglu1-mesa-dev \
              libibus-1.0-dev \
              libpulse-dev \
              libsndio-dev \
              libudev-dev \
              libwayland-dev \
              libx11-dev \
              libxcursor-dev \
              libxext-dev \
              libxi-dev \
              libxinerama-dev \
              libxkbcommon-dev \
              libxrandr-dev \
              libxss-dev \
              libxt-dev \
              libxv-dev \
              libxxf86vm-dev \
              libdrm-dev \
              libgbm-dev \
              libpulse-dev
